config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups  do
    resources :operations
  end
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  
  unauthenticated :user do
    root to: 'users#home'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, User

    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Operation, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :operations
  belongs_to :author, class_name: 'User'

  validates :name, :icon, presence: true

  def total_amount
    operations.sum(:amount)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  has_and_belongs_to_many :groups
  belongs_to :author, class_name: 'User'

  validates :name, :amount, presence: true
  validates :amount, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'author_id'
  has_many :purchases, foreign_key: 'author_id'

  validates_uniqueness_of :name, :email
  validates :name, :email, presence: true
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!
  respond_to :json, :html

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_action :authenticate_user!
  load_and_authorize_resource
  def new
    @group = Group.new
  end

  def index
    @groups = current_user.groups.all
  end

  def create
    @group = Group.new(group_params)
    current_user.groups << @group
    if @group.save
      flash[:notice] = 'group added successfully'
      redirect_to groups_path
    else
      flash[:alert] = 'group not added! please try again'
      render :new
    end
  end

  def destroy
    previous_url = request.env['HTTP_REFERER']
    group = group.find(params[:id])
    if group.destroy
      flash[:notice] = 'group successfully deleted'
    else
      flash[:alert] = 'group not deleted! please try again'
    end
    redirect_to(previous_url)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  load_and_authorize_resource
  def new
    @operation = Operation.new
  end

  def index
    @group = Group.find(params[:group_id])
    @operations = @group.operations.order('created_at DESC')
  end

  def create
    @group = Group.find(params[:group_id])
    @operation = @group.operations.create(operation_params)
    if @operation.save
      flash[:notice] = 'operation added successfully'
      redirect_to group_operations_path
    else
      flash[:alert] = 'operation not added! please try again'
      render :new
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, group_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :home

  def home
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_group.html.erb
<%= link_to group_operations_url(group), class:"category-btn" do %>
<div class="group-card has-background-color-white mx-2 mt-1 p-2 card-shadow">
	<%= image_tag(group.icon, class: "image") %>
	<div class="group_card flex flex-row flex-grow-1 flex-direction-column pl-2">
		<div class="flex flex-row justify-space-between my-2">
			<h5 class="group-name fw-regular is-flex flex-grow-1"><%= group.name %></h5>
 <small class="total-amount fw-bold">$<%= group.total_amount %></small> 
		</div>
		<small class="date"><%= group.created_at.strftime("%d %b %Y") %></small>
	</div>
</div>
<% end %>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/index.html.erb
<div class="flex flex-direction-column flex-grow-1 has-background-color">
   <nav class="navigation px-4">
    <ul class="navigation-items">
      <li>
      </li>
      <li>
        <p class="text-white font-proxima">Categories</p>
      </li>
         <li>
        <%= link_to 'logout' , destroy_user_session_url, method: :delete, class: "logout next text-white bg-transparent cursor-pointer"%>
    </li>
    </ul>
  </nav>

    <% if @groups.empty? %>
        <div class="alert alert-info">
          No categories for now !
        </div>
      <% else %>
          <%= render @groups %>
      <% end %>

 

</div>


<button class="footer_btn">
    <%= link_to 'Add a new category', new_group_path, class: "log" %>
</button>

app/views/groups/new.html.erb
<%= form_with(model: @group)  do |form| %>


    <nav class="navigation px-4">
    <ul class="navigation-items">
      <li>
        <%= link_to groups_path do %>
        <i class="back-icon fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">Category</p>
      </li>
         <li>
          <%= form.submit "Save", class: "logout next text-white bg-transparent cursor-pointer" %>
    </li>
    </ul>
  </nav>


    <div class="field">
      <%= form.text_field :name, class: 'input', placeholder: "category name", class: "input", required: true %>
    </div>
    <div class="field">
          <%= form.url_field :icon, class: 'input', placeholder: "icon url", class: "input", required: true %>
    </div>
   
  <% end %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<section class="h-screen bg-back relative">

  <nav class="bg-main py-4 px-4">
    <ul class="flex justify-between items-center">
      <li>
        <%= link_to groups_path do %>
        <i class="fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">DETAILS CATEGORY</p>
      </li>
      <li>
        <i class="fa fa-bars text-transparent cursor-pointer"></i>
      </li>
    </ul>
  </nav>

  <div class="w-full px-4 mt-4">
    <div class="p-4 space-y-4 bg-white rounded">
      <img src=<% @group.icon %> alt="group-picture">
      <h2 class="font-bold font-proxima"><%= @group.name %></h2>
      <%
=begin%>
 <p class="font-proxima"><%= @group.total_amount %> unit</p> 
<%
=end%>
      <%
=begin%>
 <div class="font-proxima">     
        <%= link_to 'Edit', edit_group_path(@group), class: 'text-white py-2 px-8
        border-2 bg-second rounded-lg cursor-pointer' %> 
<%
=end%>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
      <p class="alert alert-success text-center mb-2 msg"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/operations/_operation.html.erb
<div class="group-card has-background-color-white mx-2 mt-1 p-2 card-shadow">
	<div class="group_card flex flex-row flex-grow-1 flex-direction-column pl-2">
		<div class="flex flex-row justify-space-between my-2">
			<h5 class="group-name fw-regular is-flex flex-grow-1"><%= operation.name %></h5>
        <small class="total-amount fw-bold">$<%= operation.amount %></small> 

		</div>
		    <small class="date"><%= operation.created_at.strftime("%d %b %Y") %></small>
	    </div>
</div>

app/views/operations/index.html.erb
<div class="flex flex-direction-column flex-grow-1 has-background-color">
   <nav class="navigation px-4">
    <ul class="navigation-items">
      <li>
        <%= link_to root_path do %>
        <i class="back-icon fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">Transactions</p>
      </li>
         <li>
        <%= link_to 'logout' , destroy_user_session_url, method: :delete, class: "logout next text-white bg-transparent cursor-pointer"%>
    </li>
    </ul>

   
  </nav>
   <div class="group_informations">
        <span><%=@group.name%></span>
        <span>$ <%=@group.total_amount%></span>
        
        </div>

   

   <% if @operations.empty? %>
        <div class="alert alert-info">
          No transactions for now !
        </div>
      <% else %>
         <%= render @operations %>
      <% end %>

  

</div>


<button class="footer_btn">
    <%= link_to 'Add a new transaction', new_group_operation_path, class: "log" %>
</button>

app/views/operations/new.html.erb
<%= form_with(model:[@group, @operation],url: group_operations_path , data: { turbo: false })  do |form| %>


    <nav class="navigation px-4">
    <ul class="navigation-items">
      <li>
        <%= link_to group_operations_path do %>
        <i class="back-icon fa fa-arrow-left text-white cursor-pointer"></i>
        <%end%>
      </li>
      <li>
        <p class="text-white font-proxima">Transaction</p>
      </li>
         <li>
          <%= form.submit "Save", class: "logout next text-white bg-transparent cursor-pointer" %>
    </li>
    </ul>
  </nav>

  
    <div class="field">
      <%= form.text_field :name, class: 'input', placeholder: "transaction name", class: "input",  id:"Name", required: true %>
    </div>
    <div class="field">
          <%= form.number_field :amount, class: 'input', placeholder: "transaction amount", id:"Amount", class: "input", required: true %>
    </div>
   
  <% end %>

app/views/users/home.html.erb
<section class="contain">
    <div class="logo" >
        <%= image_tag("logo.png", class: "m-5") %>
    </div>

<div class="flex flex-col m-5 button-container">
        <button class="log-in" ><%= link_to "LOG IN",new_user_session_path, class:'log' %> </button>
       <button class="sign-up"> <%= link_to "SIGN UP",new_user_registration_path, class:'signup' %></button>
</div>
</section>